### ISSUE TITLE
Good to have you back

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#10]
When you're back again:
Hi NAME, good to have you back! (waving hand icon)
Then (maybe shorter) greeting...

**Comment by delikatessa** [comment]
I think shorter greeting would be nice. Can you think os some please?

**Comment by IchFloque** [comment]
just for when somebody is back again right?

**Comment by delikatessa** [comment]
yeah. should we add sth to "Hi NAME, good to have you back! (waving hand icon)." or this is enough actually ? on second thought this is alreday a greeting :)

**Comment by IchFloque** [comment]
Hi NAME, good to have you back! ✌ I'd love to scout some more TEDx ideas 💡for you!
Then again: How would you like to get started?

**Comment by delikatessa** [comment]
fixed. you need to restart a conversation
