### ISSUE TITLE
Add fb menu

### ISSUE THREAD

**Issue by delikatessa** [TEDxVienna/chatbot-frontend#12]
with TEDxVienna link,  help etc.

**Comment by IchFloque** [comment]
yeah, example here
![14642955_10207650713882590_1782312374_n](https://cloud.githubusercontent.com/assets/1272560/19386325/d2edd072-9213-11e6-859f-8075eb9cbf15.png)

**Comment by delikatessa** [comment]
can you provide menu elements for our bot?

**Comment by IchFloque** [comment]
is this possible already? :) sure, give me half an hour?

**Comment by delikatessa** [comment]
i might do it now 
https://developers.facebook.com/docs/messenger-platform/thread-settings/persistent-menu

**Comment by IchFloque** [comment]
what do you think:
- ℹ️ About (show very first welcome message again where he explains who he is)
- 🔎 Search TEDx talks (-> Ok, what are you interested in?)
- 💡 Inspire me (get random talks right away)
- 📖 Disclaimer (link to tedxvienna.at/ideabot-disclaimer)
- 👍 Like me (Link to Facebook Page Overview)

**Comment by IchFloque** [comment]
OH, and: 
- 🔄 Restart conversation (start with the welcome message)

**Comment by delikatessa** [comment]
max 5!

**Comment by IchFloque** [comment]
ok then forget the additional last one ;)

**Comment by delikatessa** [comment]
check menu. first icon doesn't look as expected

**Comment by IchFloque** [comment]
what do you mean? looks exactly like here to me :)

**Comment by delikatessa** [comment]
ok

**Comment by delikatessa** [comment]
@IchFloque the menu implemented  using bots global commands
you can trigger them by typing too:
about
search
inspire
restart //not in menu but works

should we add one more global command for ending conversation? sth like "bye" or

**Comment by IchFloque** [comment]
yes sure, make bye.
i will think of more tomorrow.
and also the thing where you send a thumbs up and he replies with a thumb up :)

**Comment by IchFloque** [comment]
the menu is not working any more. 
he starts typing but doesn't reply anything...

**Comment by delikatessa** [comment]
i see it too. no idea what happened now. i guess i'll better check tmr :) oops today

**Comment by delikatessa** [comment]
i'm using 👍 to thumb back. the blue fb is something completely different.

**Comment by IchFloque** [comment]
@delikatessa It's not a character, it's a sticker!
StickerID: 3692392632228

But every size has a different ID, so you need to catch all sizes:
Works like this: 

> if (stickerID.indexOf("3692392632228") === 0) ...

**Comment by delikatessa** [comment]
menu works now
