### ISSUE TITLE
Last fixes before conference

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#18]
- [x] "Would you like to get more inspiration on the last topic?" -> "on this topic" or even better "on biology" (parsed search term)
- [x] menu doesn't work any more (just typing, no answer)
- [x] thumbs up answer on blue thumbs up (see code in #12)

**Comment by delikatessa** [comment]
i'll be available on thu evening.

**Comment by IchFloque** [comment]
ok then we need to change the release to Friday :)

**Comment by delikatessa** [comment]
we do not parse search term now

**Comment by delikatessa** [comment]
Currently stickers are not supported by facebook send api: https://developers.facebook.com/docs/messenger-platform/send-api-reference

> We support multiple types multimedia and templates attachments:
> 
> image
> audio
> video
> file
> generic template
> button template
> receipt template

**Comment by IchFloque** [comment]
it definitely works, I tried it with the Austrian Airline Bot and got the sticker ID from their developer

**Comment by IchFloque** [comment]
should i ask for the exact send code line?

**Comment by IchFloque** [comment]
ok you are right. we cannot send that sticker atm.
BUT:
we can definitely read the thumb with 
`if (stickerID.indexOf("3692392632228") === 0) ...`
and reply with the normal thumbs up emoticon 👍 .

![14801178_10207952363982150_383001720_n](https://cloud.githubusercontent.com/assets/1272560/19568438/dd43afa0-96f1-11e6-835d-a56b73e0de63.jpg)

**Comment by IchFloque** [comment]
so the 2 things except thumbs is fixed? see above at the very top
