### ISSUE TITLE
Answer Buttons do not show everywhere

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#23]
A problem is that the browser version of messenger doesn't support the buttons, which is why many people get it wrong (Facebook homepage -> messages). It works on the small chat window and on messenger.com and all the apps, but not in the messenger subpage of facebook. See screenshot here. I saw the austrian airlines bot has different answer buttons, which are supported everywhere (even though the don't look so nice). See also attached 
![screen shot 2016-10-25 at 12 27 00](https://cloud.githubusercontent.com/assets/1272560/19682835/bbdc2902-9aaf-11e6-8ae5-4a8c3937707e.png)
here. Can we switch?

**Comment by IchFloque** [comment]
here the different button that should work
![screen shot 2016-10-25 at 12 27 14](https://cloud.githubusercontent.com/assets/1272560/19682853/cee9547a-9aaf-11e6-913e-6757f87e4d41.png)

**Comment by IchFloque** [comment]
@delikatessa this is the issue we talked about yesterday ;)

**Comment by delikatessa** [comment]
@IchFloque what browser are you using? I usually always tested it in the browser. Cannot reproduce.

**Comment by IchFloque** [comment]
i think safari

**Comment by IchFloque** [comment]
looks like it was fixed by itself
