### ISSUE TITLE
Max. error limit

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#24]
If a user doesn't get how to use the bot we should inform him about usage after 3 wrong inputs (within a conversation) that returned the error msg. This needs to be set to 0 after 10min or so.

**Comment by delikatessa** [comment]
it is possible to set the max retries number but i'm not sure if it's possible to reset this count. At least I didn't find it in the docu. @IchFloque what do you expect to happen after 3 failed attempts?

**Comment by IchFloque** [comment]
I'd say a message that explains how to use the bot (click the predefined answers, wait until you are asked to put in a topic etc.)

**Comment by delikatessa** [comment]
i've found a solution using Prompts.text with the msg contaning Quick replies. But this needs more advanced response handling. work in progress

**Comment by delikatessa** [comment]
can you please specify the message?
what happens after the message is displayed? show the choices again?

**Comment by IchFloque** [comment]
yes, i would display the choices again, also the question for that matter.
message proposal for now: "Sorry, I'm not sure what to do 😅. Right now you have the choices [CHOICE 1] or [CHOICE 2]. Please type what you prefer or hit one of the buttons right below."
(only if typing the choice also works as discussed in the meeting)

**Comment by delikatessa** [comment]
@juliabla added the message on the 3rd attempt. Please test with Testbot

**Comment by juliabla** [comment]
It works.

![grafik](https://cloud.githubusercontent.com/assets/11851502/22621809/5c74e5c6-eb2c-11e6-81ab-0a522a56b4b9.png)
