### ISSUE TITLE
retrieve personal facebook information

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#30]
check what is possible to store

**Comment by delikatessa** [comment]
it seems we should be able to accces the user'd public profile data. trying to retrieve it

**Comment by delikatessa** [comment]
now we save public profile info in db. example:

**Comment by delikatessa** [comment]
{
  "first_name": "name",
  "last_name": "surname",
  "profile_pic": "url",
  "locale": "en_US",
  "timezone": 1,
  "gender": "female"
}
