### ISSUE TITLE
Auto-greeting

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#4]
The bot should start with the greeting message automatically or have a "get started" button instead of the input typing field to trigger the greeting.

**Comment by delikatessa** [comment]
we can display get started button, but only on FIRST use. What kind of greeting should we display
https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

**Comment by IchFloque** [comment]
First use is fine :) "Get Started" is also good enough or did you mean the small text above the button?

**Comment by delikatessa** [comment]
ah. no text needed. Added Get Started button
