### ISSUE TITLE
New bot texts

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#5]
**Greeting:**
Hi NAME, I’m your personal idea scout, designed to help you find inspiring ideas in the form of TED and TEDx talks from all over the world! Just enter a topic you’re interested in and I’ll give you some fitting suggestions. 

How would you like to get started?
Search / Inspire me (no exclamation mark)

**Search**
Ok, what are you interested in?

After result -> 
Would you like to get more inspiration on “TOPIC” / on this topic? (use parsed topic if possible)
Sure / I’m good

Would you like to look into another topic?
Absolutely / I’m good 

I'm good -> Is there anything else you’d like to do?

**Inspire me**
People from around the world find these talks especially inspiring: -talks-
Need more inspiration?
Sure / I’m good

**Goodbye**
Thanks for dropping by! Come back anytime for a further dose of inspiration. Talk to you soon!

**Errors**
Sorry NAME, I don't understand gibberish...
(Repeat previous question.)

Your wordsmith skills are just too much for me! I didn’t get that.
(Repeat previous question.)

Oh stop it! I’m blushing. Or did I get that wrong?
(Repeat previous question.)

Asfdsjihu. Or did you mean omdjosfjsjn? Please choose one of the following options.
(Repeat previous question.)

Sorry, we didn't find anything. -> Sorry NAME, I couldn’t find anything.

"Watch" button -> "Watch now"

**Comment by delikatessa** [comment]
@IchFloque please limit greeting to 160 symbols or less

**Comment by IchFloque** [comment]
@delikatessa I’m your personal idea scout, designed to help you find inspiring ideas in the form of TED talks! Enter a topic and I’ll give you some fitting suggestions.

**Comment by IchFloque** [comment]
@delikatessa can we just use the firstname where it says NAME? 
Also the Errors Responses are missing, you you have a look again?

**Comment by delikatessa** [comment]
No way to separate the name unless we parse it. 
Error responses added.

**Comment by IchFloque** [comment]
ok let's use the substring then please! from index 0 to the first blank char. the whole name just doesn't fit the TEDx informality :)

**Comment by delikatessa** [comment]
done
