### ISSUE TITLE
Emojis for Bot Replies

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/chatbot-frontend#7]
Can we add some nice Icons?

Hi NAME, I'm your personal idea scout 🤖, designed to help you find inspiring ideas in the form of TEDx talks from all over the world 💡🌍! Just enter a topic you're interested in and I'll give you some fitting suggestions.

💡 Inspire Me
🔎 Search

Thanks for dropping by! Come back anytime for a further dose of inspiration. Talk to you soon! 👋

👍 Sure

**Comment by IchFloque** [comment]
@delikatessa 
Please also: 

- For the "I'm good" -> Make it "No, I'm good" when replying "Would you like to get more inspiration (/on this topic)".

- For the second reply afterwards ("Is there anything else you want to do?") change "Sure" and "I'm good" to "👍 Yes" and "No, thanks." So they are different options than before.

- When you say yes: "How would you like to get started?"-> Change to "What would you like to do?". But leave the "How would you like to get started?" for the very first conversation loop.

- Whenever you send the bot the Facebook Thumb Up 👍 (alone), he should answer with a 👍 again.

**Comment by IchFloque** [comment]
Do the Emoticons above work?

**Comment by delikatessa** [comment]
added emojis. 

> When you say yes: "How would you like to get started?"-> Change to "What would you like to do?". But leave the "How would you like to get started?" for the very first conversation loop.
>Whenever you send the bot the Facebook Thumb Up 👍 (alone), he should answer with a 👍 again.

tbd

**Comment by IchFloque** [comment]
the change resulted in some bugs, he doesn't recognise some answers any more 
![screen shot 2016-10-17 at 18 19 58](https://cloud.githubusercontent.com/assets/1272560/19445884/7bca03f8-9496-11e6-8ba2-42e0358bac9d.png)

**Comment by IchFloque** [comment]
and this
![screen shot 2016-10-17 at 18 20 31](https://cloud.githubusercontent.com/assets/1272560/19445916/9db130d6-9496-11e6-9bfc-1628b72f3a15.png)

**Comment by IchFloque** [comment]
the lightbulb in the first message is not working?

**Comment by IchFloque** [comment]
<img width="634" alt="screen shot 2016-10-17 at 23 19 28" src="https://cloud.githubusercontent.com/assets/1272560/19456086/2e1564c0-94c0-11e6-8189-c4c4f709a2a9.png">
still doesn't work for me, even with a new conversation. :(

**Comment by delikatessa** [comment]
that's strange how it understands "search" with emoji but not "sure". i'll check what i can do

**Comment by delikatessa** [comment]
my workaround didn't work. I removed emojis from Sure/Yes for now.

**Comment by IchFloque** [comment]
yeah makes sense. really weird.. :/
